-- Names from fake players addon https://github.com/C0nw0nk/Garrys-Mod-Fake-Players

D3bot.Names = {
	"Rainbow Dash",
	"Fluttershy",
	"Twilight Sparkle",
	"Rarity",
	"Pinky Pie",
	"AppleJack",
	"Derpy Hooves",
	"Pound Cake",
	"Mrs. Cup Cake",
	"Snips",
	"Apple Bloom",
	"Sweetie Belle",
	"Scootalo",
	"Big Macintosh",
	"Princess Luna",
	"Donald Trump",
	"Obama",
	"Gabe Newell",
	"Gaben",
	"Garry :D",
	"MKA0208",
	"FLARE MAG",
	"snooth",
	"awooomi",
	"læd"
	"Mr.Roflman 65",
	"Medical Dude",
	"taco",
	"Freddy Fatbear",
	"GlassSkunk",
	"Fee",
	"Fii",
	"Foo",
	"Fum",
	"Foo Foo",
	"Zombie with a gun",
	"Crowmauler",
	"Rubat",
	"Jaffa Cake",
	"Sweetex",
	"Nightmare",
	"Klienmare",
	"Shade",
	"Butcher",
	"Cremator",
	"Howler",
	"Tickle Monster",
	"Bonemesh",
	"The Hidden",
	"Surveyor",
	"B-zine",
	"Snark",
	"Headcrab",
	"sewer-snark",
	"rave-rat",
	"i will eat you",
	"Earthmover",
	"┌∩┐(◣_◢)┌∩┐",
	"d(^_^)b",
	"~Katt~ <3",
	"supersecretbotname",
	"coconut13",
	"The REAL Jonkler",
	"Meta",
	"Trigger",
	"T-REX",
	"Kitty",
	"Rabbit",
	"Doggy",
	"the fish",
	"sillysnake",
	"actualnoodle",
	"meow :3",
	"woof :3",
	"The G-Unit",
	"Buttercup",
	"Fluffy",
	"Foxxi ♥",
	"Defcon",
	"Xira",
	"Xenia",
	"Steam.exe",
	"Prodigy",
	"Flump",
	"Boom Headshot!",
	"Cookie",
	"Flesh Pound",
	"C4k3",
	"GirlDeaa",
	"Lemon",
	"Volition",
	"BellaTrix",
	"Atomic Boom!",
	"Nuclear Reactor Party!",
	"DION",
	"Swexy",
	"Spyro",
	"scary bot",
	"Super Man",
	"Khaleesi",
	"DYSON",
	"Pixies",
	"Rayman",
	"Andrax",
	"SpY",
	"Los Lobos",
	"Foxy",
	"Tiny Tim",
	"BASSHUNTER",
	"Scooter",
	"D00p",
	"C4sp3r",
	"Moi Loca",
	"Mina | <3",
	"Cr33p3r",
	"1+3+3=7",
	"1+1=11",
	"77+11=100",
	"Mojo Jojo",
	"Cerberus",
	"Pr0",
	"The Salt Bar",
	"Bubbles",
	"Zeus",
	"Snapshot",
	"Floofy",
	"dudette",
	"Coach",
	"TANK",
	"panda♥",
	"K9 Lady",
	"Him",
	"Soo Hungryyy",
	"Oughhhhhhh",
	"FREE FOOD",
	"Woody",
	"<3 FEMALE META | :3",
	"Shit Medics",
	"Redeem me plz",
	"Skycade Hater",
	"!SKYCADE",
	"Solocade Breaker",
	"Leroy Jenkins",
	"Skill Issue",
	"Built Different",
	"VOTE MAKO",
	"shitcader",
	"Free RPG",
	"hey beter",
	"I was a lootbag",
	"Prop Kill Incoming",
	"Headcrab Gaming",
	"pepe",
	"A Cader",
	"B Cader",
	"C cader",
	"Nerf Zombies",
	"Nerf Humans",
	"Navmesh Tester",
	"League Player",
	"Baguette",
	"Grievous Wounds Enjoyer",
	"NEST PLS",
	"UNSTUCK ME",
	"HTEAM COOKED",
	"ZTEAM COOKED",
	"Wave 1 Wipe",
	"ArthurofHex",
	"BUY ARMOR",
	"Batman",
	"Add Bots",
	"the fungus??",
	"AI Reject",
	"A Fat Slug",
	"snailharmony",
	"talking tomato",
	"fakeplayer774",
	"REPAIR"
}